import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const packagesDir = path.resolve(__dirname, '../..')

interface PluginInfo {
  name: string
  shortName: string
  version: string
  description: string
  displayName: string
}

const plugins: PluginInfo[] = []

const entries = fs.readdirSync(packagesDir, { withFileTypes: true })

for (const entry of entries) {
  if (!entry.isDirectory()) continue
  if (!entry.name.startsWith('plugin-')) continue

  const packageJsonPath = path.join(packagesDir, entry.name, 'package.json')

  try {
    const content = fs.readFileSync(packageJsonPath, 'utf-8')
    const pkg = JSON.parse(content)

    if (pkg.gitton) {
      plugins.push({
        name: pkg.name,
        shortName: entry.name.replace('plugin-', ''),
        version: pkg.version,
        description: pkg.gitton.description || pkg.description || '',
        displayName: pkg.gitton.displayName || pkg.name
      })
    }
  } catch {
    // Skip invalid packages
  }
}

const output = `// Auto-generated by scripts/generate-plugin-list.ts
// Do not edit manually

export interface PluginInfo {
  name: string
  shortName: string
  version: string
  description: string
  displayName: string
}

export const availablePlugins: PluginInfo[] = ${JSON.stringify(plugins, null, 2)}
`

const outputPath = path.join(__dirname, '../src/generated/plugins.ts')
fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, output)

console.log(`Generated plugin list with ${plugins.length} plugins`)
